### ISSUE TITLE
General question(s) about usage and usability

### ISSUE THREAD

**Issue by EvilBMP** [christianfutterlieb/backend_roles#5]
Hi,

I just stumbled upon this extension and I really like the idea behind it. Keeping backend usergroups synchronized via dev/stage and prod is a real pain. I just wanted to share my ideas/ complaints about the current usage and usability. Please correct me, if I am just using it "the wrong way" or I didn't get "your" idea behind it.

If I map a backend role to a backend usergroup, than normally that usergroup cannot be configured anymore through the backend ui - unless you disable the checkbox/ switch in the main extension configuration/ settings of the extension.

Wouldn't it be nicer to have one YAML (~or PHP~) file for each role <-> usergroup mapping instead of one big file?
Something like `./config/backend-roles/<identifier>.yaml` or `./config/backend-roles/<usergroup-uid>.yaml` (latter would allow sync without an additional identifier, but would be less "readable")?! So something similar to the sites configuration backend module.

Then the extension could be used to write/ update the usergroup configuration to this file directly and not only serve the current configuration as download. That would allow to adjust the backend usergroup configuration in the same way as it's done right now in general via backend ui. So an integrator could do the work of configuring the backend usergroups and then simply export all usergoup configurations to their respective file.

These files could then be used to synchronize the settings with staging and production systems. So the CLI command also would only need to check, whether a matching file is available or not.

That above mentioned checkbox/ switch then could be enabled on production and/ or staging sites. But even if not, so that a manual override of usergroup settings in production/ staging environments would still be allowed, I don't see any problems here. Sure any future deployment which would trigger the synchronization of roles <-> usegroups would overwrite this former manual override via backend ui. But that should be covered by the development team to update missing access rights in the role yaml files via local development environment and than push that to VCS for the next release.

Any thoughts?

**Comment by christianfutterlieb** [comment]
Hi,

Thanks for your interest in the extension :-) To your questions/suggestions:

**Configuration file structure**: that has been a point in discussion, when I developed the YAML-support feature. I decided to go for the one file approach, because of these points:
1. I'd rather scan for an exact filename than for *.yaml in an exact directory (giving better control over what is loaded and avoids security problems)
2. The YAML loader in TYPO3 supports inclusion of other files, like this it is possible to have one YAML file per role (see https://docs.typo3.org/p/christianfutterlieb/backend_roles/main/en-us/Configuration/RoleDefinition.html#example-one-file-per-role-definition). That is at least what I do (and recommend).

**Using the role filename as role identifier** in be_groups: I'd rather have the identifier configured in a role, than inferring it from a filename. It would not be reliable enough and would introduce too much configuration "magic".

**Write configuration files from within the Backend Module**: that is completely against the intent of this extension. The be_roles records should be updated according to the definition, not the other way around.

> That above mentioned checkbox/ switch then could be enabled on production and/ or staging sites

It is meant to always be enabled. Making changes to a synchronized be_groups record in any other environment than dev (where the definition will/should be updated accordingly) should be avoided. Otherwise the reliability of the definitions is rendered useless. If you really really have the need to change access rights in stage/prod environments, rather use a separate be_groups record for that, not a synchronized one. With the export function you can give any changes back to the development team, where they can integrate it into the definitions.

I hope I clarified your points. While reading your ideas, I had another one, that I think I'm going to implement: showing the sync-status of a synchronized be_groups record. Maybe with a green icon overlay for "sync ok" and a yellow one for "out of sync".

Regards, Christian
